#\!/usr/bin/env python3
"""Test modal layout structure"""

print("Modal Layout Structure (after changes):")
print("=" * 50)
print("")
print("┌─ Histogram Container (95% x 90%) ─────────────┐")
print("│ ┌─ Header ──────────────────────────────────┐ │")
print("│ │ Latency Histogram: column_name | Filters  │ │")
print("│ └────────────────────────────────────────────┘ │")
print("│                                                │")
print("│ ┌─ ScrollableContainer ─────────────────────┐ │")
print("│ │ ┌─ Heatmap Section (FIRST) ──────────────┐│ │")
print("│ │ │ [bold]Time-Series Heatmap:[/bold]      ││ │")
print("│ │ │     66ms │ ░░░░▒▒▓▓████                ││ │")
print("│ │ │     33ms │ ░░░▒▒▓████                  ││ │")
print("│ │ │     16ms │ ░░▒▒▓████                   ││ │")
print("│ │ │    256μs │ ░▒▓████                     ││ │")
print("│ │ │    128μs │ ▒▓████                      ││ │")
print("│ │ │     64μs │ ▓████                       ││ │")
print("│ │ │     16μs │ ████                        ││ │")
print("│ │ │      8μs │ ████                        ││ │")
print("│ │ │      4μs │ ████                        ││ │")
print("│ │ │      2μs │ ▒▒▒                         ││ │")
print("│ │ └─────────────────────────────────────────┘│ │")
print("│ │                                             │ │")
print("│ │ ┌─ Table Section (SECOND) ────────────────┐│ │")
print("│ │ │ [bold]Latency Distribution Table:[/bold]││ │")
print("│ │ │                                         ││ │")
print("│ │ │ Latency Range  Count  Events/s  Time % ││ │")
print("│ │ │ ─────────────────────────────────────  ││ │")
print("│ │ │      2μs-4μs     100    50000    10%   ││ │")
print("│ │ │      4μs-8μs     200   100000    20%   ││ │")
print("│ │ │     8μs-16μs     150    75000    15%   ││ │")
print("│ │ │    (no border, zebra stripes)          ││ │")
print("│ │ │    (no cursor navigation)              ││ │")
print("│ │ └─────────────────────────────────────────┘│ │")
print("│ └─────────────────────────────────────────────┘ │")
print("│                                                │")
print("│ [Footer: ESC/Q close, SPACE toggle granularity]│")
print("└────────────────────────────────────────────────┘")
print("")
print("✓ Heatmap section shows FIRST")
print("✓ Table section shows SECOND")
print("✓ DataTable has no border, no cursor")
print("✓ Both sections have consistent formatting")
print("✓ Entire modal is scrollable vertically")
