/*
 *  0x.Tools xCapture - sample thread activity from Linux procfs [https://0x.tools]
 *  Copyright 2019-2025 Tanel Poder
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *
 * NOTES:
 *
 *  full architecture-specific syscall list in Linux kernel source:
 *  arch/arm64/tools/syscall_64.tbl
 *  or run ausyscall --dump or parse unistd.h
 *
 *   awk '/^[0-9]/{ printf("[%4d] = {\"%s\", \"%s\"},\n", $1, $2, $3); }' < arch/arm64/tools/syscall_64.tbl
 */

#ifndef __XCAPTURE_SYSCALL_NAMES_H
#define __XCAPTURE_SYSCALL_NAMES_H

typedef struct sysent {
    const char *abi;
    const char *name;
} struct_sysent;

const struct_sysent sysent0[] = {
[   0] = {"common", "io_setup"},
[   1] = {"common", "io_destroy"},
[   2] = {"common", "io_submit"},
[   3] = {"common", "io_cancel"},
[   4] = {"64", "io_getevents"},
[   5] = {"common", "setxattr"},
[   6] = {"common", "lsetxattr"},
[   7] = {"common", "fsetxattr"},
[   8] = {"common", "getxattr"},
[   9] = {"common", "lgetxattr"},
[  10] = {"common", "fgetxattr"},
[  11] = {"common", "listxattr"},
[  12] = {"common", "llistxattr"},
[  13] = {"common", "flistxattr"},
[  14] = {"common", "removexattr"},
[  15] = {"common", "lremovexattr"},
[  16] = {"common", "fremovexattr"},
[  17] = {"common", "getcwd"},
[  18] = {"common", "lookup_dcookie"},
[  19] = {"common", "eventfd2"},
[  20] = {"common", "epoll_create1"},
[  21] = {"common", "epoll_ctl"},
[  22] = {"common", "epoll_pwait"},
[  23] = {"common", "dup"},
[  24] = {"common", "dup3"},
[  25] = {"64", "fcntl"},
[  26] = {"common", "inotify_init1"},
[  27] = {"common", "inotify_add_watch"},
[  28] = {"common", "inotify_rm_watch"},
[  29] = {"common", "ioctl"},
[  30] = {"common", "ioprio_set"},
[  31] = {"common", "ioprio_get"},
[  32] = {"common", "flock"},
[  33] = {"common", "mknodat"},
[  34] = {"common", "mkdirat"},
[  35] = {"common", "unlinkat"},
[  36] = {"common", "symlinkat"},
[  37] = {"common", "linkat"},
[  38] = {"renameat", "renameat"},
[  39] = {"common", "umount2"},
[  40] = {"common", "mount"},
[  41] = {"common", "pivot_root"},
[  42] = {"common", "nfsservctl"},
[  43] = {"64", "statfs"},
[  44] = {"64", "fstatfs"},
[  45] = {"64", "truncate"},
[  46] = {"64", "ftruncate"},
[  47] = {"common", "fallocate"},
[  48] = {"common", "faccessat"},
[  49] = {"common", "chdir"},
[  50] = {"common", "fchdir"},
[  51] = {"common", "chroot"},
[  52] = {"common", "fchmod"},
[  53] = {"common", "fchmodat"},
[  54] = {"common", "fchownat"},
[  55] = {"common", "fchown"},
[  56] = {"common", "openat"},
[  57] = {"common", "close"},
[  58] = {"common", "vhangup"},
[  59] = {"common", "pipe2"},
[  60] = {"common", "quotactl"},
[  61] = {"common", "getdents64"},
[  62] = {"64", "lseek"},
[  63] = {"common", "read"},
[  64] = {"common", "write"},
[  65] = {"common", "readv"},
[  66] = {"common", "writev"},
[  67] = {"common", "pread64"},
[  68] = {"common", "pwrite64"},
[  69] = {"common", "preadv"},
[  70] = {"common", "pwritev"},
[  71] = {"64", "sendfile"},
[  72] = {"64", "pselect6"},
[  73] = {"64", "ppoll"},
[  74] = {"common", "signalfd4"},
[  75] = {"common", "vmsplice"},
[  76] = {"common", "splice"},
[  77] = {"common", "tee"},
[  78] = {"common", "readlinkat"},
[  79] = {"64", "newfstatat"},
[  80] = {"64", "fstat"},
[  81] = {"common", "sync"},
[  82] = {"common", "fsync"},
[  83] = {"common", "fdatasync"},
[  84] = {"common", "sync_file_range"},
[  85] = {"common", "timerfd_create"},
[  86] = {"64", "timerfd_settime"},
[  87] = {"64", "timerfd_gettime"},
[  88] = {"64", "utimensat"},
[  89] = {"common", "acct"},
[  90] = {"common", "capget"},
[  91] = {"common", "capset"},
[  92] = {"common", "personality"},
[  93] = {"common", "exit"},
[  94] = {"common", "exit_group"},
[  95] = {"common", "waitid"},
[  96] = {"common", "set_tid_address"},
[  97] = {"common", "unshare"},
[  98] = {"64", "futex"},
[  99] = {"common", "set_robust_list"},
[ 100] = {"common", "get_robust_list"},
[ 101] = {"64", "nanosleep"},
[ 102] = {"common", "getitimer"},
[ 103] = {"common", "setitimer"},
[ 104] = {"common", "kexec_load"},
[ 105] = {"common", "init_module"},
[ 106] = {"common", "delete_module"},
[ 107] = {"common", "timer_create"},
[ 108] = {"64", "timer_gettime"},
[ 109] = {"common", "timer_getoverrun"},
[ 110] = {"64", "timer_settime"},
[ 111] = {"common", "timer_delete"},
[ 112] = {"64", "clock_settime"},
[ 113] = {"64", "clock_gettime"},
[ 114] = {"64", "clock_getres"},
[ 115] = {"64", "clock_nanosleep"},
[ 116] = {"common", "syslog"},
[ 117] = {"common", "ptrace"},
[ 118] = {"common", "sched_setparam"},
[ 119] = {"common", "sched_setscheduler"},
[ 120] = {"common", "sched_getscheduler"},
[ 121] = {"common", "sched_getparam"},
[ 122] = {"common", "sched_setaffinity"},
[ 123] = {"common", "sched_getaffinity"},
[ 124] = {"common", "sched_yield"},
[ 125] = {"common", "sched_get_priority_max"},
[ 126] = {"common", "sched_get_priority_min"},
[ 127] = {"64", "sched_rr_get_interval"},
[ 128] = {"common", "restart_syscall"},
[ 129] = {"common", "kill"},
[ 130] = {"common", "tkill"},
[ 131] = {"common", "tgkill"},
[ 132] = {"common", "sigaltstack"},
[ 133] = {"common", "rt_sigsuspend"},
[ 134] = {"common", "rt_sigaction"},
[ 135] = {"common", "rt_sigprocmask"},
[ 136] = {"common", "rt_sigpending"},
[ 137] = {"64", "rt_sigtimedwait"},
[ 138] = {"common", "rt_sigqueueinfo"},
[ 139] = {"common", "rt_sigreturn"},
[ 140] = {"common", "setpriority"},
[ 141] = {"common", "getpriority"},
[ 142] = {"common", "reboot"},
[ 143] = {"common", "setregid"},
[ 144] = {"common", "setgid"},
[ 145] = {"common", "setreuid"},
[ 146] = {"common", "setuid"},
[ 147] = {"common", "setresuid"},
[ 148] = {"common", "getresuid"},
[ 149] = {"common", "setresgid"},
[ 150] = {"common", "getresgid"},
[ 151] = {"common", "setfsuid"},
[ 152] = {"common", "setfsgid"},
[ 153] = {"common", "times"},
[ 154] = {"common", "setpgid"},
[ 155] = {"common", "getpgid"},
[ 156] = {"common", "getsid"},
[ 157] = {"common", "setsid"},
[ 158] = {"common", "getgroups"},
[ 159] = {"common", "setgroups"},
[ 160] = {"common", "uname"},
[ 161] = {"common", "sethostname"},
[ 162] = {"common", "setdomainname"},
[ 163] = {"rlimit", "getrlimit"},
[ 164] = {"rlimit", "setrlimit"},
[ 165] = {"common", "getrusage"},
[ 166] = {"common", "umask"},
[ 167] = {"common", "prctl"},
[ 168] = {"common", "getcpu"},
[ 169] = {"64", "gettimeofday"},
[ 170] = {"64", "settimeofday"},
[ 171] = {"64", "adjtimex"},
[ 172] = {"common", "getpid"},
[ 173] = {"common", "getppid"},
[ 174] = {"common", "getuid"},
[ 175] = {"common", "geteuid"},
[ 176] = {"common", "getgid"},
[ 177] = {"common", "getegid"},
[ 178] = {"common", "gettid"},
[ 179] = {"common", "sysinfo"},
[ 180] = {"common", "mq_open"},
[ 181] = {"common", "mq_unlink"},
[ 182] = {"64", "mq_timedsend"},
[ 183] = {"64", "mq_timedreceive"},
[ 184] = {"common", "mq_notify"},
[ 185] = {"common", "mq_getsetattr"},
[ 186] = {"common", "msgget"},
[ 187] = {"common", "msgctl"},
[ 188] = {"common", "msgrcv"},
[ 189] = {"common", "msgsnd"},
[ 190] = {"common", "semget"},
[ 191] = {"common", "semctl"},
[ 192] = {"64", "semtimedop"},
[ 193] = {"common", "semop"},
[ 194] = {"common", "shmget"},
[ 195] = {"common", "shmctl"},
[ 196] = {"common", "shmat"},
[ 197] = {"common", "shmdt"},
[ 198] = {"common", "socket"},
[ 199] = {"common", "socketpair"},
[ 200] = {"common", "bind"},
[ 201] = {"common", "listen"},
[ 202] = {"common", "accept"},
[ 203] = {"common", "connect"},
[ 204] = {"common", "getsockname"},
[ 205] = {"common", "getpeername"},
[ 206] = {"common", "sendto"},
[ 207] = {"common", "recvfrom"},
[ 208] = {"common", "setsockopt"},
[ 209] = {"common", "getsockopt"},
[ 210] = {"common", "shutdown"},
[ 211] = {"common", "sendmsg"},
[ 212] = {"common", "recvmsg"},
[ 213] = {"common", "readahead"},
[ 214] = {"common", "brk"},
[ 215] = {"common", "munmap"},
[ 216] = {"common", "mremap"},
[ 217] = {"common", "add_key"},
[ 218] = {"common", "request_key"},
[ 219] = {"common", "keyctl"},
[ 220] = {"common", "clone"},
[ 221] = {"common", "execve"},
[ 222] = {"64", "mmap"},
[ 223] = {"64", "fadvise64"},
[ 224] = {"common", "swapon"},
[ 225] = {"common", "swapoff"},
[ 226] = {"common", "mprotect"},
[ 227] = {"common", "msync"},
[ 228] = {"common", "mlock"},
[ 229] = {"common", "munlock"},
[ 230] = {"common", "mlockall"},
[ 231] = {"common", "munlockall"},
[ 232] = {"common", "mincore"},
[ 233] = {"common", "madvise"},
[ 234] = {"common", "remap_file_pages"},
[ 235] = {"common", "mbind"},
[ 236] = {"common", "get_mempolicy"},
[ 237] = {"common", "set_mempolicy"},
[ 238] = {"common", "migrate_pages"},
[ 239] = {"common", "move_pages"},
[ 240] = {"common", "rt_tgsigqueueinfo"},
[ 241] = {"common", "perf_event_open"},
[ 242] = {"common", "accept4"},
[ 243] = {"64", "recvmmsg"},
[ 260] = {"64", "wait4"},
[ 261] = {"common", "prlimit64"},
[ 262] = {"common", "fanotify_init"},
[ 263] = {"common", "fanotify_mark"},
[ 264] = {"common", "name_to_handle_at"},
[ 265] = {"common", "open_by_handle_at"},
[ 266] = {"64", "clock_adjtime"},
[ 267] = {"common", "syncfs"},
[ 268] = {"common", "setns"},
[ 269] = {"common", "sendmmsg"},
[ 270] = {"common", "process_vm_readv"},
[ 271] = {"common", "process_vm_writev"},
[ 272] = {"common", "kcmp"},
[ 273] = {"common", "finit_module"},
[ 274] = {"common", "sched_setattr"},
[ 275] = {"common", "sched_getattr"},
[ 276] = {"common", "renameat2"},
[ 277] = {"common", "seccomp"},
[ 278] = {"common", "getrandom"},
[ 279] = {"common", "memfd_create"},
[ 280] = {"common", "bpf"},
[ 281] = {"common", "execveat"},
[ 282] = {"common", "userfaultfd"},
[ 283] = {"common", "membarrier"},
[ 284] = {"common", "mlock2"},
[ 285] = {"common", "copy_file_range"},
[ 286] = {"common", "preadv2"},
[ 287] = {"common", "pwritev2"},
[ 288] = {"common", "pkey_mprotect"},
[ 289] = {"common", "pkey_alloc"},
[ 290] = {"common", "pkey_free"},
[ 291] = {"common", "statx"},
[ 292] = {"64", "io_pgetevents"},
[ 293] = {"common", "rseq"},
[ 294] = {"common", "kexec_file_load"},
[ 403] = {"32", "clock_gettime64"},
[ 404] = {"32", "clock_settime64"},
[ 405] = {"32", "clock_adjtime64"},
[ 406] = {"32", "clock_getres_time64"},
[ 407] = {"32", "clock_nanosleep_time64"},
[ 408] = {"32", "timer_gettime64"},
[ 409] = {"32", "timer_settime64"},
[ 410] = {"32", "timerfd_gettime64"},
[ 411] = {"32", "timerfd_settime64"},
[ 412] = {"32", "utimensat_time64"},
[ 413] = {"32", "pselect6_time64"},
[ 414] = {"32", "ppoll_time64"},
[ 416] = {"32", "io_pgetevents_time64"},
[ 417] = {"32", "recvmmsg_time64"},
[ 418] = {"32", "mq_timedsend_time64"},
[ 419] = {"32", "mq_timedreceive_time64"},
[ 420] = {"32", "semtimedop_time64"},
[ 421] = {"32", "rt_sigtimedwait_time64"},
[ 422] = {"32", "futex_time64"},
[ 423] = {"32", "sched_rr_get_interval_time64"},
[ 424] = {"common", "pidfd_send_signal"},
[ 425] = {"common", "io_uring_setup"},
[ 426] = {"common", "io_uring_enter"},
[ 427] = {"common", "io_uring_register"},
[ 428] = {"common", "open_tree"},
[ 429] = {"common", "move_mount"},
[ 430] = {"common", "fsopen"},
[ 431] = {"common", "fsconfig"},
[ 432] = {"common", "fsmount"},
[ 433] = {"common", "fspick"},
[ 434] = {"common", "pidfd_open"},
[ 435] = {"common", "clone3"},
[ 436] = {"common", "close_range"},
[ 437] = {"common", "openat2"},
[ 438] = {"common", "pidfd_getfd"},
[ 439] = {"common", "faccessat2"},
[ 440] = {"common", "process_madvise"},
[ 441] = {"common", "epoll_pwait2"},
[ 442] = {"common", "mount_setattr"},
[ 443] = {"common", "quotactl_fd"},
[ 444] = {"common", "landlock_create_ruleset"},
[ 445] = {"common", "landlock_add_rule"},
[ 446] = {"common", "landlock_restrict_self"},
[ 447] = {"memfd_secret", "memfd_secret"},
[ 448] = {"common", "process_mrelease"},
[ 449] = {"common", "futex_waitv"},
[ 450] = {"common", "set_mempolicy_home_node"},
[ 451] = {"common", "cachestat"},
[ 452] = {"common", "fchmodat2"},
[ 453] = {"common", "map_shadow_stack"},
[ 454] = {"common", "futex_wake"},
[ 455] = {"common", "futex_wait"},
[ 456] = {"common", "futex_requeue"},
[ 457] = {"common", "statmount"},
[ 458] = {"common", "listmount"},
[ 459] = {"common", "lsm_get_self_attr"},
[ 460] = {"common", "lsm_set_self_attr"},
[ 461] = {"common", "lsm_list_modules"},
[ 462] = {"common", "mseal"},
};

#define NR_SYSCALLS sizeof(sysent0) / sizeof(sysent0[0])

#endif /* __XCAPTURE_SYSCALL_NAMES_H */
